---
title: "With_vs_without_air"
author: "Brandon Titensor"
date: "2024-06-04"
output: pdf_document
---

```{r}
with_air1 <- read_csv("~/Desktop/College/Research/With_vs_without_air/with_air1.csv")
with_air2 <- read_csv("~/Desktop/College/Research/With_vs_without_air/with_air2.csv")
with_air3 <- read_csv("~/Desktop/College/Research/With_vs_without_air/with_air3.csv")
with_air4 <- read_csv("~/Desktop/College/Research/With_vs_without_air/with_air4.csv")

without_air1 <- read_csv("~/Desktop/College/Research/With_vs_without_air/without_air1.csv")
without_air2 <- read_csv("~/Desktop/College/Research/With_vs_without_air/without_air2.csv")
without_air3 <- read_csv("~/Desktop/College/Research/With_vs_without_air/without_air3.csv")
without_air4 <- read_csv("~/Desktop/College/Research/With_vs_without_air/without_air4.csv")

with_air <- rbind(with_air1,with_air2,with_air3,with_air4)
without_air <- rbind(without_air1,without_air2,without_air3,without_air4)

with_air$type <- ifelse(with_air$Area < 0.00001963495, "artifact",  ifelse(with_air$Circ. > 0.99, "artifact", "dust"))
without_air$type <- ifelse(without_air$Area < 0.0000196349, "artifact",  ifelse(without_air$Circ. > 0.99, "artifact", "dust"))

particle_with <- with_air$type == "artifact"
particle_without <- without_air$type == "artifact"

with_air<- with_air[particle_with == "FALSE",]
without_air<- without_air[particle_without == "FALSE",]

with_air$Diameter <- (sqrt(with_air$Area/pi)*2)*1000
without_air$Diameter <- (sqrt(without_air$Area/pi)*2)*1000

```

```{r}
summary(with_air$Area)
summary(without_air$Area)

par(mfrow = c(1, 2))
hist(with_air$Area, main = "With Air:Area", breaks = 10000, xlim = c(0, .0005))
hist(without_air$Area, main = "Without Air:Area", breaks = 10000, xlim = c(0, .0005))

boxplot(with_air$Area, main = "With Air:Area")
boxplot(without_air$Area, main = "Without Air:Area")
```

```{r}
summary(with_air$Circ.)
summary(without_air$Circ.)

par(mfrow = c(1, 2))
hist(with_air$Circ., main = "With Air:Circularity", breaks = 100)
hist(without_air$Circ., main = "Without Air:Circularity", breaks = 100)

boxplot(with_air$Circ., main = "With Air:Circularity")
boxplot(without_air$Circ., main = "Without Air:Circularity")
```

```{r}
summary(with_air$Diameter)
summary(without_air$Diameter)

# 5.614-((10.32-5.614)*1.5)
# 10.32+((10.32-5.614)*1.5)
# 
# 5.653-((8.675-5.653)*1.5)
# 8.675+((8.675-5.653)*1.5)

diameter_subset1 <- with_air[with_air$Diameter>=0,]
diameter_subset1 <- diameter_subset1[diameter_subset1$Diameter<=17.379,]

diameter_subset2 <- without_air[without_air$Diameter>=1.12,]
diameter_subset2 <- diameter_subset2[diameter_subset2$Diameter<=13.208,]

par(mfrow = c(1, 2))
hist(with_air$Diameter, main = "With Air:Diameter", breaks = 100, xlim = c(0, 100))
hist(without_air$Diameter, main = "Without Air:Diameter", breaks = 100, xlim = c(0, 100))

boxplot(with_air$Diameter, main = "With Air:Diameter")
boxplot(without_air$Diameter, main = "Without Air:Diameter")

hist(diameter_subset1$Diameter, main = "With Air:Diameter", breaks = 100, xlim = c(0, 20))
hist(diameter_subset2$Diameter, main = "Without Air:Diameter", breaks = 100, xlim = c(0, 20))

boxplot(diameter_subset1$Diameter, main = "With Air:Diameter")
boxplot(diameter_subset2$Diameter, main = "Without Air:Diameter")

```


```{r}
# Define the bin edges for particle size
bin_edges <- c(5, 15, 25, 50, 100, 250, 500, 750, 1000, 1250)

# Create a new column "size_bin" in the data frame
# and assign the corresponding bin to each particle based on its diameter
with_air$size_bin <- cut(with_air$Diameter, breaks = bin_edges, right = FALSE,
                     labels = c("5-15", "15-25", "25-50", "50-100", "100-250", "250-500",
                                "500-750", "750-1000", "1000-1250"))

# Create a summary table with the count of particles in each size bin
size_bin_table <- table(with_air$size_bin)

# Print the summary table
print(size_bin_table)
```

```{r}
# Define the bin edges for particle size
bin_edges <- c(5, 15, 25, 50, 100, 250, 500, 750, 1000, 1250)

# Create a new column "size_bin" in the data frame
# and assign the corresponding bin to each particle based on its diameter
without_air$size_bin <- cut(without_air$Diameter, breaks = bin_edges, right = FALSE,
                     labels = c("5-15", "15-25", "25-50", "50-100", "100-250", "250-500",
                                "500-750", "750-1000", "1000-1250"))

# Create a summary table with the count of particles in each size bin
size_bin_table <- table(without_air$size_bin)

# Print the summary table
print(size_bin_table)
```

